  
title: p5 clock
author: cipherDOT
email: r.m.kavinbharathi@gmail.com
description: clock using p5


github_username:  cipherDOT

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
